name: stratified-manifold-learning
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core ML libraries
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - torchaudio>=0.9.0
  
  # Scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  
  # NLP and Transformers
  - transformers>=4.20.0
  - datasets>=2.0.0
  - tokenizers>=0.12.0
  - sentencepiece>=0.1.96
  
  # Dimensionality reduction
  - umap-learn>=0.5.0
  
  # Progress bars and utilities
  - tqdm>=4.62.0
  
  # Jupyter support
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # Development tools
  - pytest>=6.0.0
  - black>=21.0.0
  - flake8>=3.9.0
  
  # Additional utilities
  - fsspec>=2021.8.0
  
  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    - accelerate>=0.20.0
    - bitsandbytes>=0.37.0
    - openai>=0.27.0
    - huggingface-hub>=0.10.0
    - kaleido>=0.2.1
    - ripser>=0.6.0
    - persim>=0.3.0
    - gudhi>=3.4.0
    - Cython>=0.29.0
